version: v1.0

fail_fast: true
plan: professional-1

global_job_config:
  setup:
    - curl -o /tmp/$FILE_NAME.vp9 $SOURCE_INPUT
  jobs:
    - name: Conversion
      commands:
        - ffmpeg -i /tmp/$FILE_NAME.vp9 -c:v libx264 -c:a aac -preset ultrafast -r 25 -crf 23 -g 250 -tune film -vprofile high -pix_fmt yuv420p -movflags +faststart /tmp/$FILE_NAME.mp4

triggers:
  - event: api
