version: v1.0

fail_fast: true
plan: professional-1

envs:
  - key: SOURCE_INPUT
    value: https://d2tagele5v9dwg.cloudfront.net/31ebb876-cb20-4aea-9872-8c098a43eb7b/92c93be5-3ae1-44ba-a56d-615191d8c9ec/3066da4d-5124-4e12-937e-8fb0deae43a9
  - key: S3_BUCKET
    value: neeto-record-mp4-recordings-staging
  - key: FILE_PATH
    value: 31ebb876-cb20-4aea-9872-8c098a43eb7b/92c93be5-3ae1-44ba-a56d-615191d8c9ec
  - key: FILE_NAME
    value: 3066da4d-5124-4e12-937e-8fb0deae43a9

global_job_config:
  setup:
    - echo "Downloading the file from the given source input"
    - curl -o /tmp/$FILE_NAME.vp9 $SOURCE_INPUT
  jobs:
    - name: MP4 Conversion
      commands:
        - echo "Converting the given VP9 file to MP4"
        - ffmpeg -i /tmp/$FILE_NAME.vp9 -c:v libx264 -c:a aac -preset ultrafast -r 25 -crf 23 -g 250 -tune film -vprofile high -pix_fmt yuv420p -movflags +faststart /tmp/$FILE_NAME.mp4

triggers:
  - event: api
