---
plan_slug: standard-2
triggers:
- event: branch
  branch_name: main
- event: pull_request
commands:
- checkout
- neetoci-version ruby 3.3.5
- neetoci-version node 18.12
- neetoci-service start postgres 18
- neetoci-service start redis 7.0.5
- cp config/database.yml.ci config/database.yml
- bundle config path 'vendor/bundle'
- bundle install --jobs 1
- yarn install
- bundle exec rake db:create db:schema:load --trace
- bundle exec rails test
- bundle exec rake setup
